### ISSUE TITLE
MKS TFT24 Size

### ISSUE THREAD

**Issue by BuddaBob** [makerbase-mks/MKS-TFT#146]
I'm looking Forum a Datasheet with Sizes of the TFT 24 nur i cant find anything.
For the other TFTs i cant find them.
Ist there nothing Out?

**Comment by Jinxycob** [comment]
they have  drawing with sizes  on ali https://tinyurl.com/yd2tyccu scroll down you see it, but i found the drawing was in error! the sd card slot was on the right hand side rather than the left,, could be an option to rotate the screen in firmware but i didn't see it.
correction just discovered : 
#Screen rotation 180 °(0:disable,1:enable)
>cfg_OVERTURN_180:0
solved tht

**Comment by makerbase-mks** [comment]
we will fix it.
