### ISSUE TITLE
TFT32 Blank white screen

### ISSUE THREAD

**Issue by FBReality** [makerbase-mks/MKS-TFT#147]
Hello
My screen stay full white, when I reset or restart, I have a white screen, a black , a beep and return to white, nothing more
I tried to update firmware but nothing change
One time when I pressed on screen, my printer start to move but I don't know what I do to have this.
Seems screen work but show nothing.
If you have any idea
Thanks in advance

**Comment by makerbase-mks** [comment]
What is the version of software and hardware.

**Comment by FBReality** [comment]
Hardware 3.0
Software, I tried 3.0.1 and 3.0.2, same result

**Comment by makerbase-mks** [comment]
The screen may be damaged, you can contact our sales replacement TFT.

**Comment by mageta90** [comment]
Hello i have the same issues.

screen built in in a jgaurora printer. worked fine for 3 months, then out of the blue the screen is all white.
tried to upload the original firmware, then the 3.0.1 but no change.

the same behavior of FBReality's one

hardware is 3.0

The firmware is actually updating, because the files in the SD get names changed .

**Comment by mageta90** [comment]
no idea of what's appening here?

**Comment by Vorchak** [comment]
Is there an update on this issue? I have the exact same symptoms. The screen is all white, however, I noticed that the icons are still there just not visible. And they even respond to touch.

**Comment by FBReality** [comment]
No news, finally I bought a new one that works perfectly, and from a shop where I can get a real warranty
