### ISSUE TITLE
TFT Display 2.8 v3.0.3 firmware for "retro" doesn't work

### ISSUE THREAD

**Issue by TheSimplyCode** [makerbase-mks/MKS-TFT#235]
Whenever I want to download the Firmware 3.0.3 "Retro/mkstft28.bin" the display shows an error. In the upgrade manager of the firmware! With "Classic/mkstft28.bin" it works.

**Comment by makerbase-mks** [comment]
the display shows an error?can you show it by the picture?

**Comment by TheSimplyCode** [comment]
Here are two pictures of the display, one with the error and one with the display version:
![img_5426](https://user-images.githubusercontent.com/45294783/49286814-92838080-f49b-11e8-850c-83b3a7803b17.JPG)
![img_5427](https://user-images.githubusercontent.com/45294783/49286816-931c1700-f49b-11e8-86d5-d2104bdb3937.JPG)

I used following configuration of TFT28_32_v3.0.3 Release:
-mks_config_EN.txt renamed to mks_config.txt
-Retro/mkstft28.bin
-MksWifi.bin
-mks_font
-Red style/mks_pic

thanks

**Comment by sergioe23** [comment]
I have the same error, it happens with Retro/mkstft28.bin, doesn't matter what style i use.

**Comment by makerbase-mks** [comment]
Hello Killerage,
I'm not sure what the issue is but I'll try to help.
To change the configuration of the Robin you need to change the config file when it is in TEXT FILE (.txt) format and then save that to your sd card, put it in the Robin and then turn on power to start the Robin. When the Robin starts it reads the .txt file makes the changes to the firmware settings and then it edits the file extension type so that it does read it again. If you want to changes the settings again then the config file needs to be in the .txt format or at startup the Robin ignores the file.
To set your steps per mm use the Prusa calculator for x, y and z.
Find that here>>>https://www.prusaprinters.org/calculator/
E is calibrated by running some filament through the extruder and measuring how much went through.
I hope this helps but if not repost and we can try again.
Matt

**Comment by makerbase-mks** [comment]
The hardware version is too low, the next firmware version will be compatible with this older version of the hardware
