### ISSUE TITLE
second extruder not displaying on screen

### ISSUE THREAD

**Issue by EWGRage** [makerbase-mks/MKS-TFT#282]
I cant get my second extruder to show on the screen for me to control and it is usine E0 as E1?

**Comment by gysnst2** [comment]
I have the same issue even after updating the config file

**Comment by makerbase-mks** [comment]
Probably because you have dual extruder single nozzle of your configuration file. So you can only see the temperature of a heating head
#Whether to support the function of dual extruder single nozzle.(0: disable, 1: enable)
#the extruder number need set to dual.
>cfg_single_nozzle:0

disable  it  and you can see the second  extruder
