### ISSUE TITLE
For the South Korean user, how could I adopt the Korean font for MKS-TFT 3.5 firmware?

### ISSUE THREAD

**Issue by makerssi** [makerbase-mks/MKS-TFT#301]
Hello

This is Jack from Makerssi Co.,Ltd., the company manufactures FDM printer in South Korea.
Recently we adopted MKS-TFT 3.5" screen to our new product and it works just fine.
But for Korean users, we'd like to change the LCD firmware language from English to Korean.

Can you give us any tip for changing the language for LCD firmware of MKS-TFT 3.5"?
Please guide us and it will be great if it could be changed into South Korean language... We really anticipating the method for this! 

Hope to get feedback from MKS-TFT R&D team.
Thank you so much for reading this.

From Jack Jang (jack@makerssi.co.kr)

**Comment by makerbase-mks** [comment]
Because the 7 languages that are commonly used now almost fill the space of the chip, it is usually necessary to eliminate one if a new language is added, so generally this requires firmware customization.
If you have any customization needs in this regard, you can contact this email address.
caixindong@makerbase.com.cn
