### ISSUE TITLE
MKS TFT32_L no communication with MKS SGEN_L

### ISSUE THREAD

**Issue by karnalta** [makerbase-mks/MKS-TFT#345]
Hi,

I have upgraded my Ender 3 with the tft32 and sgen_l but I can’t get them to communicate.

On the sgen_l I have installed the Marlin 2.0 prepared by mks and only inverted the end stop and axis from configuration.h. The board seem to work fine, when plugged via USB I can control the printer.

The TFT has been flashed without problem and set on the same speed than marlin. It look to function well but can’t communicate with the board. I can’t do anything to the printer from the lcd.

Is there specific step to take to make them work together ?

Thank for help

**Comment by makerbase-mks** [comment]
1、This problem is similar：https://github.com/makerbase-mks/MKS-Robin/issues/113
2、You need set on configuration.h file of Marlin2.0：
/**
 * Select the serial port on the board to use for communication with the host.
 * This allows the connection of wireless adapters (for instance) to non-default port pins.
 * Note: The first serial port (-1 or 0) will always be used by the Arduino bootloader.
 *
 * :[-1, 0, 1, 2, 3, 4, 5, 6, 7]
 */
#define SERIAL_PORT -1

/**
 * Select a secondary serial port on the board to use for communication with the host.
 * This allows the connection of wireless adapters (for instance) to non-default port pins.
 * Serial port -1 is the USB emulated serial port, if available.
 *
 * :[-1, 0, 1, 2, 3, 4, 5, 6, 7]
 */
#define SERIAL_PORT_2 0
