### ISSUE TITLE
Several bugs and questions

### ISSUE THREAD

**Issue by javikas** [makerbase-mks/MKS-TFT#346]
I've tried to set the second cmd button in settings screen but It doesn't work.
Both the datasheet and the comment in mks_config.txt says "user-defined function1 and 2." but only button 1 does actually work.
So defining _cfg_function_btn2_display_ and _function_btn2_cmd_ does nothing.

I've opened the bin file with an hex editor and I can confirm neither the commands nor _bmp_function2.bin_ are used at all (classic, retro nor simple). So what about that?

On the other hand, what's the font folder for? _GBK16.bin_ and _UNIGBK.bin_ are not called either. The actual font used by the firmware is embedded in _mkstft28.bin_ so... what are they for and why do you include in the release?

Another issue that I don't understand is why don't you let the user to remove the wifi button if no module is installed. I've bought an Artillery Sidewinder X1 and they have just changed the wifi icon for their logo to "hide" the fact that they don't provide wifi

I've managed to modify the font and menu names by modifying the binary (hardcoding new hex values). Do you have a solution to the rest of bugs that I'm pointing or you just don't mind about them?

**Comment by makerbase-mks** [comment]
1. The  function2 has already canceled ,because the language button occupies the position, and you can do the second function in more.and we will fix the datasheet.
2. Fonts We use the Song style, the font is released together to avoid a user need to re-write the font, you can directly delete the mks_font folder if you don't need it.
3. In the latest firmware, the wifi function can be enabled or disabled via the button, but the icon is still displayed on the screen. Your suggestion will be considered in the next release.
