### ISSUE TITLE
Wifi with Home assistant?

### ISSUE THREAD

**Issue by JeedHome44** [makerbase-mks/MKS-TFT#446]
Hello,

Can we connect the TFT screen with the wifi module to Home assistant to automate the printer locally and not in the cloud?

Thank you

**Comment by makerbase-mks** [comment]
Yes! you can.

**Comment by JeedHome44** [comment]
How please?
You have an addon in Home Assistant?

**Comment by makerbase-mks** [comment]
Can you provide config to me?

**Comment by nlubello** [comment]
Hi!
I'm interested too in the integration of MKS in Home Assistant.
I have an FlyingBear ghost 5 and wifi is working ok with Cura MKS plugin.
What configuration is needed?

**Comment by willpuckett** [comment]
I would like to see more info on this thread... Getting these printers in home assistant without having to use Octoprint would be 👍

**Comment by TheSimpleZ** [comment]
@JeedHome44 Did you ever figure out how to do this integration? If yes, it would be great if you could either provide some instructions. Otherwise, could you please re-open this issue so it can be tracked? There are still others like me who are looking to get this integration working.

@makerbase-mks What config are you looking for? We're asking you to provide us with the configuration steps necessary to integrate MKS TFT Wifi with Home assistant. Usually, that would be through an official integration or some HACS component.  
You should not need our personal configs to provide such a thing.
