### ISSUE TITLE
MKS TFT 32 Firmware will not update 

### ISSUE THREAD

**Issue by usajet** [makerbase-mks/MKS-TFT#74]
I load the firmware files onto the SD card as instructed and it only shows booting and not updating on the screen.

**Comment by Ioshikazu** [comment]
Hi, the same here with me. Did you found any solution?

**Comment by usajet** [comment]
Yes you need at least a 2 GB or lower SD card.

**Comment by HugoW1975** [comment]
Hi, I just dowloaded these files:
https://github.com/robotsrulz/MKS-TFT
And put them on my 4GB USB stick, trying to update the firmware on my TFT because at the moment it is in Chinese. I start the system with the USB stick in place, screen connected to the MKS SBase V1.3. It just starts, no update. What should I do?
Cheers,
Hugo

**Comment by usajet** [comment]
Use a 2 GB or lower SD Card.

**Comment by zen** [comment]
Try SD card, not USB stick

**Comment by MarkV3082** [comment]
Lifesaver thanks
